version: "3"

services:

  api:
    build: .
    image: api
    ports: 
      - "3000:3000"
    volumes:
      - ./:/home/node/app/
    networks:
      - mic-bridge
    depends_on: 
      - db


  db:
    image: mongo
    ports: 
      - "27017:27017"
    networks:
      - mic-bridge

networks:
  mic-bridge:
    external: true